.\" Man page Go Package Manager (warp)

.TH warp 1 "December 2023" "Go Package Manager 1.0" "User Commands"

.SH NAME
warp \- Go Package Manager

.SH SYNOPSIS
\fBwarp\fR [\fIcommand\fR] [\fIoptions\fR] [\fIarguments\fR]

.SH DESCRIPTION
The \fBwarp\fR command is a custom package manager designed to manage packages for your project.

.SH COMMANDS
.TP
\fBinstall\fR [\fIpackage\fR]
Install the specified package.

.TP
\fBuninstall\fR [\fIpackage\fR]
Uninstall the specified package.

.SH OPTIONS
.TP
\fB-h, --help\fR
Show this help message.

.TP
\fB-v, --version\fR
Show the version of \fBwarp\fR.

.SH EXAMPLES
Install a package:
.PP
\fBwarp install my-package\fR


Uninstall a package:
.PP
\fBwarp uninstall my-package\fR


.SH AUTHOR
Codezz-ops <codezz-ops@protonmail.com>

.SH BUGS
Report bugs at: \fIhttps://github.com/Codezz-ops/PackageManager/issues\fR

.SH COPYRIGHT
Copyright \(co 2023 Codezz-ops. This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

.SH LICENSE
This program is distributed under the terms of the GPL-2.0 License. See the LICENSE file for details.

.SH NOTES
This man page is a basic template. Customize it based on the features and commands your package manager supports.
